{% set name = "PyPDF2" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyPDF2-{{ version }}.tar.gz
  sha256: a74408f69ba6271f71b9352ef4ed03dc53a31aa404d29b5d31f53bfecfee1440

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.10.0.0
    - dataclasses

test:
  requires:
    - python {{ python_min }}
  imports:
    - PyPDF2


about:
  home: http://py-pdf.github.io/PyPDF2/
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  dev_url: https://github.com/py-pdf/PyPDF2
  license: BSD-3-Clause
  doc_url: https://pypdf2.readthedocs.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
    - pmlandwehr
    - carlodri
