{% set name = "PyPDF2" %}
{% set version = "1.27.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1fd4a200fb2a6634c7a027d678ea52c634e4b41d90c4c573530af3911964ad4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - PyPDF2

about:
  home: http://py-pdf.github.io/PyPDF2/
  license: BSD-3-Clause  # unsure about this license...to be rechecked
  license_file: LICENSE
  license_family: BSD
  summary: A utility to read and write PDFs with Python
  doc_url: https://pypdf2.readthedocs.io/
  dev_url: https://github.com/py-pdf/PyPDF2

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
