{% set name = "PyPDF2" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyPDF2-{{ version }}.tar.gz
  sha256: 340dcc7fd62ad3dc4a132df13617e9c33f1c4c15379846cb95ef14aec9f106f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - typing_extensions >=3.10.0.0 
    - dataclasses

test:
  imports:
    - PyPDF2
  

about:
  home: http://py-pdf.github.io/PyPDF2/
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  dev_url: https://github.com/py-pdf/PyPDF2
  license: BSD-3-Clause
  doc_url: https://pypdf2.readthedocs.io/
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
    - pmlandwehr
    - carlodri
