{% set name = "PyPDF2" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 340dcc7fd62ad3dc4a132df13617e9c33f1c4c15379846cb95ef14aec9f106f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - PyPDF2

about:
  home: http://py-pdf.github.io/PyPDF2/
  license: BSD-3-Clause  # unsure about this license...to be rechecked
  license_file: LICENSE
  license_family: BSD
  summary: A utility to read and write PDFs with Python
  doc_url: https://pypdf2.readthedocs.io/
  dev_url: https://github.com/py-pdf/PyPDF2

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
