travis:
  secure:
    BINSTAR_TOKEN: gSv4QZqUcP/iSV1UKGGs5fhuHJfmYuht5JrcV6HSsAoLlxA5RfgMk2KBaL8k5HdNf+Nq/pZCa5EXsZYJgs6aulQwkja25L9cQpqaJ4Q7e2IfFsLdcBKOLhiBOKO2aRVxDRVWWaYx5dUeVB1ItF5Fi9qi27P1NlNswF6M1urvaqrgGM8dL2yuCohg8ZFg6fqS1Fy+xhYgoOzCOl4QPRWh6XPLOWOwNBfPQeS3QIWPWoF9V0NKMYH/Kepc+kkW8DD6S/9hbuADYVf7UWMLNZ5GzREwjyjRk3wEjmFlsKppXTdl8Olsjldiq6eM/lBOCAunDwOXEXyibw6Xyqa4SIFqwMqIn4eOBreETUfL/a8+u04GBkFGMid3Hn5ff++IAu4QT81p48Ic/TPLxfEY8U/+riSQfa/FdIDox60EVHPWLi6KGl7ewYgKQoQ6DGyrB9jXiYUUjTTz3feMA3XXLOS9qR4hhhidkKRwm1iMYPFLJOBZjh5QVVqLmrF9e8jk42DZx7kxvOxbD1HBgnSQ797OvasxeXLU3qIwW7rzTsy00/0x8t8SgjLERSsSBKH9hCO5eqkXnBayuEUzR2X2yq37ajuJDEyxVrAg5bfgI8kkxD1NXClsnrtDDiQ6VMhdg6+Vm+UrOBGWbzUMXJbA1HKhABH92YxCGxStM3PNPZ6o0CE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
